apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 31001
  selector:
    app: prometheus
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: ConfigMap 
metadata:
  name: prom-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
      
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus 
    spec:
      containers:
      - image: prom/prometheus:latest 
        name: prometheus 
        args:
        - '--config.file=/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        ports:
        - containerPort: 9090
          name: prometheus 
        volumeMounts:
        - name: prometheus-storage
          mountPath: /prometheus 
        - name: prometheus-script 
          mountPath: /prometheus.yml
          subPath: prometheus.yml 
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prom-pv
      - name: prometheus-script 
        configMap:
            name: prom-config



